# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='current_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tender_categories',
            field=models.ManyToManyField(to='app.Tender'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tender',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
