# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170826_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
